---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mqtt
  namespace: default
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      name: mqtt
      labels:
        app: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto
          ports:
            - name: port1
              containerPort: 1883
            - name: port2
              containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
  name: mqtt
  namespace: default
spec:
  selector:
    app: mqtt
  type: NodePort
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
      nodePort: 31883
      name: port1
    - port: 31901
      protocol: TCP
      targetPort: 9001
      nodePort: 31901
      name: port2
