#####################################################################################
# Two-node RabbitMQ cluster using auto-cluster plugin and K8S DNS/Service discovery.
#
# This artifact creates the namespace, service account, and (too broad) authorization
# for the auto-cluster plugin to locate service endpoints.
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rabbitmq
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: default
