#####################################################################################
# Two-node RabbitMQ cluster using auto-cluster plugin and K8S DNS/Service discovery.
#
# These artifacts provide the two services:
#   rabbitmq-cluster - for the cluster bits
#   rabbitmq         - "external" for clients and management
#
# The deployment sets up the environment variables and 2 replicas.

#####################################################################################
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
    nodePort: 30102
    name: mqtt
  - port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 30100
    name: client
  - port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 30101
    name: management
#####################################################################################
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-cluster
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 4369
    protocol: TCP
    targetPort: 4369
    name: epmd
  - port: 25672
    protocol: TCP
    targetPort: 25672
    name: cluster
#####################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccount: rabbitmq
      serviceAccountName: rabbitmq
      containers:
      - name: rabbit
        image: alex.local:15000/rabbit:2
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: AUTOCLUSTER_CLEANUP
            value: "true"
          - name: CLEANUP_INTERVAL
            value: "60"
          - name: CLEANUP_WARN_ONLY
            value: "false"
          - name: AUTOCLUSTER_TYPE
            value: k8s
          - name: AUTOCLUSTER_LOG_LEVEL
            value: debug
          - name: K8S_SERVICE_NAME
            value: rabbitmq-cluster
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: RABBITMQ_ERLANG_COOKIE
            value: thevortex
          - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
            value: -setcookie thevortex
        ports:
          - containerPort: 1883
            name: mqtt
          - containerPort: 4369
            name: epmd
          - containerPort: 5671
            name: tls
          - containerPort: 5672
            name: aqmp
          - containerPort: 15672
            name: management
          - containerPort: 25672
            name: cluster
        livenessProbe:
          tcpSocket:
            port: 25672
          initialDelaySeconds: 60
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 15
          timeoutSeconds: 5

