#####################################################################################
# Single node Rabbit MQ server.
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbit
        image: {{ docker-repo }}/{{ docker-image }}
        ports:
          - containerPort: 1883
            name: mqtt
          - containerPort: 4369
            name: epmd
          - containerPort: 5671
            name: tls
          - containerPort: 5672
            name: aqmp
          - containerPort: 15672
            name: management
          - containerPort: 25672
            name: cluster
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
    nodePort: 30102
    name: mqtt
  - port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 30100
    name: client
  - port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 30101
    name: management
  selector:
    app: rabbitmq
  type: NodePort
