---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gogs
  labels:
    app: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - name: gogs
        image: gogs/gogs-rpi:latest
        ports:
          - containerPort: 22
            name: ssh
          - containerPort: 3000
            name: management
        volumeMounts:
          - mountPath: /data
            name: nfs-git
      volumes:
        - name: nfs-git
          persistentVolumeClaim:
            claimName: nfs-git
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gogs
  name: gogs
  namespace: default
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 30022
    name: ssh
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30023
    name: management
  selector:
    app: gogs
  type: NodePort

