---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-git
  labels:
    app: gogs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3
    - rw
    - hard
    - intr
    - rsize=8192
    - wsize=8192
  nfs:
    path: /volume1/Ops/git
    server: 192.168.1.127
