---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-git
  labels:
    app: gogs
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: gogs
